[package]
name = "nott-a-database-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
nott-a-database-core = { path = "../nott-a-database-core" }
anyhow = "1.0.94"
clap = { version = "4.5.21", features = ["derive"] }
refinery = { version = "0.8.14", features = ["rusqlite"] }
rusqlite = "0.31"
