[jobs.run-cli]
command = [
    "cargo",
    "run",
    "--color",
    "always",
    "--",
    "2024/2025",
    "./test.db",
    "--result",
    "./sample_0A.xlsx",
    "--award",
    "./sample_0B.xlsx",
    "--resit-may",
    "./sample_0C.xlsx",
    "--resit-aug",
    "./sample_0D.xlsx",
]
need_stdout = true

[keybindings]
r = "job:run-cli"
