[package]
name = "nott-a-database"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "0.26.1"
quick-xml = { version = "0.37.0", features = ["serialize"] }
serde = { version = "1.0.214", features = ["derive"] }
zip = "2.2.0"
