name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-rs:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Rust Cache
      uses: swatinem/rust-cache@v2
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf 
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-js:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
    - name: Install JS Dependencies
      run: cd nott-a-database && bun install
    - name: JS Formatting
      run: cd nott-a-database && bun run build
