name: Format Code

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format-rs:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Rust Cache
      uses: swatinem/rust-cache@v2
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
    - name: Rust Formatting
      run: cargo fmt -- --check

  format-js:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
    - name: Install JS Dependencies
      run: cd nott-a-database && bun install --dev
    - name: JS Formatting
      run: cd nott-a-database && bunx prettier src index.html --check
