name: Link Code

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf 
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
    - name: Rust Lints
      run: cargo clippy -- -Dwarnings
    - name: JS Lints
      run: cd nott-a-database && bun run lint
